Feature/hydra dvc poetry
DigicaSolutions/machine-learning-template pull request #8
Opened 2023-03-16 14:23 UTC by krzysztofwolk-digica

Implemented:

- Basic dvc config
- Poetry init

Readme is modified clariant copy.

2023-03-21 12:22 UTC, igorzaton-digica approved these changes
Nie mam uwag, nie znalazłem też żadnych błędów w README.

2023-03-21 15:15 UTC, karolinawarycha-digica requested changes

2023-03-21 15:15 UTC, karolinawarycha-digica commented on README.md
this file includes a lot of generic starting tips which can be useful to use in every project but I'm not 100% sure if they should be in the README. the chances that sb will actually read them are higher but these are some guides about how to write the code. Digica Hub seems like an alternative.
If you decide to leave it here I would suggest to make use of a table of contents.

2023-04-05 11:00 UTC, krzysztofwolk-digica commented
@krzysztofkrenc-digica jedziesz

2023-04-05 11:03 UTC, krzysztofwolk-digica commented on README.md
Well, I do not have a strong opinion on that topic tbh, hub seems good as well. @JamieChojnacki  , @krzysztofkrenc-digica

2023-04-06 09:39 UTC, krzysztofkrenc-digica commented on README.md
Then maybe it should be in a different repo? The goal here is to make DVC more accessible and I think this README is a "good start". What I'm missing here are some example dvc.yaml, params.yaml files that could be played with and changed to the user's liking, but should work out of the box. Another possibility is to make them run but raise something like DVCNotImplementedError. But at any rate, we need some small working example here and it won't work on DigicaHUB.

2023-04-06 09:39 UTC, krzysztofkrenc-digica commented on README.md
> +To create pipeline You should:
```suggestion
To create pipeline you should:
```

2023-04-10 12:43 UTC, krzysztofwolk-digica commented on README.md
> +- use `git commit` to store version of algorithm
Well, I need Instructions how to do it as well... Can you do it?

2023-04-10 13:20 UTC, krzysztofwolk-digica commented
I tried to simplify the readme. Please review agian.

2023-04-12 12:51 UTC, karolinawarycha-digica approved these changes

2023-04-12 12:51 UTC, karolinawarycha-digica commented on README.md
> +4. Adjust local_remote path in .dvc/config
trochę nie rozumiem tych zawirowań z wielką i małą literą na początku, ale poza tym chyba ok :)

2023-04-26 10:18 UTC, krzysztofkrenc-digica approved these changes
Please, add missing newlines.

2023-04-26 10:23 UTC, merged